project:
  type: website
  output-dir: docs

website:
  title: "Vamshi Krishna"
  back-to-top-navigation: true

  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: Research
        href: research.qmd

      - text: Publications
        href: publications.qmd

      - text: Contact
        href: contact.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR_LINKEDIN_PROFILE
      - icon: github
        href: https://github.com/YOUR_GITHUB_USERNAME
      - icon: "google scholar"
        href: https://scholar.google.com/citations?user=YOUR_SCHOLAR_ID
      - icon: envelope
        href: mailto:your.email@example.com

  page-footer:
    center:
      - text: "Â© 2025 Vamshi Krishna"

format:
  html:
    theme: cosmo
    css: [
          "styles.css",
          "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
          "http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900",
          ]
    toc: true